#local profile
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?serverTimezone=UTC
    username: root
    password: GOTjob@123
    driver-class-name: com.mysql.cj.jdbc.Driver