#prod profile
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://puppychatdb.cshychaanbiw.us-east-2.rds.amazonaws.com/pupchat
    username: puppy
    password: PuppyChatUser123

    #pupchat