#local profile
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?serverTimezone=UTC
    username: jerm
    password: zip
    driver-class-name: com.mysql.cj.jdbc.Driver